# Generated by Django 4.2.4 on 2023-09-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
